import type { Metadata } from "next";
import "./globals.css";
import Header from "./Components/Header";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider signInUrl="/auth" signUpUrl="/auth">
      <html lang="en">
        <body className="bg-[--background]">
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
